FROM python:3.10-slim
LABEL maintainer Wendy

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y vim

COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install cryptography

COPY . .

RUN chmod +x docker-entrypoint-dev.sh
ENTRYPOINT ["./docker-entrypoint-dev.sh"]
